book/urls.py
from django.conf.urls import patterns, url

from book import views
from book import auth_views as auth
from book import old_views as old
from book.feeds import BookFeed

urlpatterns = patterns('',
    # index
    url(r'^$', views.index, name='index'),
    url(r'^tab/(\w+)$', views.index_tab),
    url(r'^book/(?P<book_id>[0-9]+)/rss/$', BookFeed()),

    # book
    url(r'^book/(\d+)$', views.book, name='book'),
    url(r'^book/recommend/(\d+)$', views.book_recommend),
    url(r'^book/comment/save$', views.book_comment_save),
    url(r'^book/comment/remove', views.book_comment_remove),
    url(r'^buy/(\d+)$', views.buy),
    url(r'^buy/save$', views.buy_save),

    # page
    url(r'^(\d+)$', views.page, name='page'),
    url(r'^page/comment/save$',         views.page_comment_save),
    url(r'^page/comment/edit/(\d+)$',   views.page_comment_edit),
    url(r'^page/comment/remove',        views.page_comment_remove),

    # edit
    url(r'^edit/book/(\d+)$', views.edit_book),
    url(r'^edit/book/save$', views.edit_book_save),
    url(r'^edit/book/new$', views.edit_book_new),
    url(r'^edit/book/user$', views.edit_book_user),
    url(r'^edit/book/user/add$', views.edit_book_user_add),
    url(r'^edit/book/user/del$', views.edit_book_user_del),

    url(r'^edit/page/(\d+)$', views.edit_page),
    url(r'^edit/page/save$', views.edit_page_save),
    url(r'^edit/page/new/(\d+)$', views.edit_page_new),
    url(r'^edit/page/image/upload$', views.edit_page_image_upload),
    url(r'^edit/page/image/del$', views.edit_page_image_del),
    url(r'^edit/preview$', views.edit_preview),

    # profile
    url(r'^profile/(\d+)$', 'book.profile_views.info'),
    url(r'^profile/edit/base$', 'book.profile_views.edit_base'),
    url(r'^profile/edit/password$', 'book.profile_views.edit_password'),
    url(r'^profile/edit/book$', 'book.profile_views.book'),
    url(r'^profile/edit/comment$', 'book.profile_views.comment'),
    url(r'^profile/edit/comment/remove$', 'book.profile_views.remove_comment'),

    # help
    url(r'^help/(\w+)$', views.help),

    # feedback
    url(r'^feedback$', views.feedback),

    # --------------------------------------------

    # authentication
    url(r'^loginForm$', auth.loginForm),
    url(r'^logout$', auth.logout),
    url(r'^joinForm$', auth.joinForm),
    url(r'^login$', auth.login),
    url(r'^join$', auth.join),
    url(r'^passwdForm$', auth.passwdForm),
    url(r'^passwd/send$', auth.passwd_send),

    # social login
    url(r'^login/auth$', auth.social_auth),
    url(r'^login/auth/error$', auth.social_auth_error),

    # old
    url(r'^read', views.index),

    # old api
    url(r'^api/page/(\d+)$', old.api_page),
    url(r'^api/toc$', old.api_toc),
    url(r'^api/comment$', old.api_comment),
)

wikidocs/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.views.generic.base import RedirectView

from book import views
from book.models import Book, Page

admin.autodiscover()

def get_sitemap():
    book_dict = {
        'queryset': Book.objects.filter(open_yn="Y"),
        'date_field': 'create_time',
    }

    page_dict = {
        'queryset': Page.objects.filter(book__open_yn="Y", open_yn="Y"),
        'date_field': 'modify_time',
    }

    sitemaps = {
        'docs': GenericSitemap(book_dict, priority=0.5),
        'page': GenericSitemap(page_dict, priority=0.5),
    }
    return sitemaps


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wikidocs.views.home', name='home'),
    url(r'', include('book.urls')),
    url(r'', include('social_auth.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': get_sitemap()}),

    url(r'^apps/', RedirectView.as_view(url='/', permanent=False), name='index'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if not settings.DEBUG:
#     urlpatterns += patterns('',
#         url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': settings.BASE_DIR+"/book/static", 'show_indexes': True})
#     )

handler404 = views.page_404
handler500 = views.page_500

book/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Max
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.html import format_html

import datetime
import os


class Ip(models.Model):
    ip = models.CharField(max_length=30, unique=True, db_index=True)

    def __unicode__(self):
        return self.ip


OPEN_YN_CHOICES = (
    ("Y", u"공개"),
    ("N", u"비공개"),
)
ADV_YN_CHOICES = (
    ("Y", u"예"),
    ("N", u"아니오"),
)
CCL_LEFT = (
    ("by", u"예"),
    ("by-nc", u"아니오"),
)
CCL_RIGHT = (
    ("-", u"예"),
    ("-sa", u"동일한 이용허락조건을 적용하는 경우에만"),
    ("-nd", u"아니오"),
)
class Book(models.Model):
    user = models.ManyToManyField(User, verbose_name=u"저자")
    creator = models.ForeignKey(User, related_name="book_creator", verbose_name=u"지은이")
    subject = models.CharField(max_length=100, verbose_name=u"책 제목")
    create_time = models.DateTimeField(default=datetime.datetime.now)
    modify_time = models.DateTimeField(default=datetime.datetime.now)
    viewer = models.ManyToManyField(Ip, null=True, related_name="book_viewer")
    recommend = models.ManyToManyField(Ip, null=True, related_name="book_recommend")
    open_yn = models.CharField(max_length=1, default="N", choices=OPEN_YN_CHOICES, verbose_name=u"공개/비공개")
    image = models.ImageField(upload_to="book/", null=True, verbose_name=u"책 이미지")
    summary = models.TextField(null=True, blank=True, verbose_name=u"책 설명")
    ccl_left = models.CharField(max_length=20, null=True, choices=CCL_LEFT, verbose_name=u"저작물의 영리목적 이용을 허락합니까?")
    ccl_right = models.CharField(max_length=20, null=True, choices=CCL_RIGHT, verbose_name=u"저작물의 변경을 허락합니까?")
    adv_yn = models.CharField(max_length=1, default="N", choices=ADV_YN_CHOICES, verbose_name=u"광고를 표시합니까?")
    adv_content = models.TextField(null=True, blank=True, verbose_name=u"광고 내용")
    adv_mobile_content = models.TextField(null=True, blank=True, verbose_name=u"모바일 광고 내용")

    def __unicode__(self):
        return self.subject

    def ccl(self):
        nvl = lambda s: '' if s is None else str(s)
        result = nvl(self.ccl_left) + nvl(self.ccl_right)
        if result and result[-1] == "-": result = result[:-1]
        return result

    def price(self):
        sell = Sell.objects.filter(book=self)
        if sell: return sell[0].price
        return 0

    def get_absolute_url(self):
        return "/book/{0}".format(self.id)

    def get_first_page(self):
        if self.page_set.count() > 0:
            result = self.page_set.filter(open_yn='Y').order_by("seq")
            if result: return result[0]
        return ""

    def is_sell(self):
        return Sell.objects.filter(book=self).count() > 0

    def is_owner(self, user):
        return user in self.user.all()

    def is_creator(self, user):
        return user == self.creator

    def safe_image(self):
        if not self.image: return "no_image.gif"
        else: return self.image

    def get_plain_authors(self):
        result = []
        for user in self.user.all():
            result.append(user.first_name)
        return ", ".join(result)

    def last_modify_time(self):
        result = Page.objects.filter(book=self).aggregate(max=Max('modify_time'))
        return result.get('max', "")

    def recent_page_comments(self, limit=10):
        return PageComment.objects.filter(page__book=self).order_by("-create_time")[:limit]

    def recent_pages(self, limit=10):
        return self.page_set.filter(open_yn='Y').order_by("-modify_time")[:limit]


def get_upload_path(instance, filename):
    if isinstance(instance, PageImage):
        return os.path.join("page", "%d" % instance.page.id, filename)
    else:
        # return "page/%s/%s" % (instance.id, filename)
        return os.path.join("page", "%d" % instance.id, filename)


class Page(models.Model):
    subject = models.CharField(max_length=100, verbose_name=u"제목")
    content = models.TextField(verbose_name=u"내용")
    book = models.ForeignKey(Book, verbose_name=u"책선택")
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name=u"부모페이지")
    create_time = models.DateTimeField(default=datetime.datetime.today)
    modify_time = models.DateTimeField(default=datetime.datetime.today)
    viewer = models.ManyToManyField(Ip, null=True, related_name="page_viewer")
    open_yn = models.CharField(max_length=1, default="Y", choices=OPEN_YN_CHOICES, verbose_name=u"공개/비공개")
    seq = models.IntegerField(default=0)
    depth = models.IntegerField(default=0)
    image = models.ImageField(upload_to=get_upload_path, null=True, blank=True, verbose_name=u"이미지삽입")

    def __unicode__(self):
        return self.subject


    def subject_margin(self):
        return self.depth * 20

    def depth_subject(self):
        return format_html(u'<span style="padding-left: {0}px;">{1}</span>',
                           self.subject_margin(),
                           self.subject)

    def get_absolute_url(self):
        return "/{0}".format(self.id)

    def _make_parents(self, page, pages=None):
        if page.parent and page.parent != page:
            pages.insert(0, page.parent)
            self._make_parents(page.parent, pages)

    def get_parents(self):
        result = []
        self._make_parents(self, result)
        return result

    def prev(self):
        try:
            return Page.objects.filter(book=self.book, seq__lte=self.seq-1, open_yn="Y").order_by("-seq")[0]
        except:
            return ""

    def next(self):
        try:
            return Page.objects.filter(book=self.book, seq__gte=self.seq+1, open_yn="Y").order_by("seq")[0]
        except:
            return ""

    def is_closed_for_buy(self):
        return self.open_yn == "N" and self.book.is_sell()


class PageImage(models.Model):
    page = models.ForeignKey(Page)
    image = models.ImageField(upload_to=get_upload_path, null=True, blank=True, verbose_name=u"이미지")


class Sell(models.Model):
    book = models.ForeignKey(Book)
    price = models.IntegerField()
    filename =  models.CharField(max_length=100, verbose_name=u"파일명")

    def __unicode__(self):
        return self.book.subject


SEND_YN_CHOICES = (
    ("Y", u"발송완료"),
    ("N", u"미발송"),
)

MONEY_YN_CHOICES = (
    ("Y", u"입금완료"),
    ("N", u"미입금"),
)
class Buy(models.Model):
    book = models.ForeignKey(Book)
    buyer = models.CharField(max_length=100, verbose_name=u"구매자")
    email = models.CharField(max_length=200, verbose_name=u"이메일")
    telno = models.CharField(max_length=20, verbose_name=u"전화번호")
    create_time = models.DateTimeField(default=datetime.datetime.today, verbose_name=u"구매일시")
    send_yn = models.CharField(max_length=1, default="N", choices=SEND_YN_CHOICES, verbose_name=u"발송여부")
    money_yn = models.CharField(max_length=1, default="N", choices=MONEY_YN_CHOICES, verbose_name=u"입금여부")

    def __unicode__(self):
        return u"%s(%s) - %s (%s원)" % (self.buyer, self.email, self.telno, self.book.price())


class BookComment(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name=u"작성자", null=True, blank=True)
    book = models.ForeignKey(Book)
    content = models.TextField(verbose_name=u"댓글내용")
    create_time = models.DateTimeField(default=datetime.datetime.today)


class PageComment(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name=u"작성자", null=True, blank=True)
    page = models.ForeignKey(Page)
    content = models.TextField(verbose_name=u"댓글내용")
    create_time = models.DateTimeField(default=datetime.datetime.today)


@receiver(post_delete, sender=PageImage)
def photo_post_delete_handler(sender, **kwargs):
    pageImage = kwargs['instance']
    storage, path = pageImage.image.storage, pageImage.image.path
    storage.delete(path)

book/forms.py
# -*- coding: utf-8 -*-
from django import forms

class BookEditForm(forms.Form):
    subject = forms.CharField(max_length=100, required=True, label=u"책 제목")


class PageEditForm(forms.Form):
    subject = forms.CharField(max_length=100, required=True, label=u"페이지 제목")
    content = forms.CharField(required=True, label=u"페이지 내용")


class BuyForm(forms.Form):
    buyer = forms.CharField(max_length=100, required=True, label=u"신청자 이름")
    email = forms.EmailField(max_length=100, required=True, label=u"이메일")
    telno = forms.RegexField(max_length=15, regex=r"\d{2,3}[-]\d{3,4}[-]\d{4}", required=True, label=u"전화번호")
    agree = forms.BooleanField(required=True, label=u"환불규정")

book/templates/profile/profile_book.html
{% extends "profile/profile_layout.html" %}
{% load staticfiles %}
{% load summary %}

{% block edit_js %}
    <script type="text/javascript" src="{% static "pagination/jquery.pagination.js" %}"></script>
    <script type="text/javascript" src="{% static "profile/js/info.js" %}"></script>
{% endblock %}

{% block edit_css %}
    <link type="text/css" href="{% static "pagination/pagination.css" %}" rel="stylesheet"/>
    <link type="text/css" href="{% static "profile/css/info.css" %}" rel="stylesheet"/>
{% endblock %}


{% block profile_edit_content %}
    {% include "book/include/message.html" %}

    <strong>나의 책</strong>
    <hr />
    <div id="recent_books">
        {% for book in books %}
            <div class="question-line">
                <div class="row">
                    {% if not request.mobile %}
                        <div class="col-md-2">
                            <div class="book-image-box">
                                <img src="{{ MEDIA_URL }}/{{ book.safe_image }}" class="book-image"
                                     onclick="javascript:location.href='{{ book.get_absolute_url }}'"
                                     style="cursor:pointer"/>
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-md-10">
                        <div>
                            <a href="/book/{{ book.id }}" class="question-subject">{{ book.subject }}</a>
                        </div>

                        <div class="question-summary">
                            저자: {{ book.get_plain_authors }}
                        </div>

                        {% if request.mobile %}
                            <div class="question-summary">
                                {{ book.summary|summary|truncatechars:"80" }}
                            </div>
                        {% else %}
                            <div class="question-summary">
                                {{ book.summary|summary|truncatechars:"160" }}
                            </div>
                        {% endif %}

                        <div class="info-timesince">
                            수정: {{ book.modify_time }}
                        </div>

                        <div style="margin-top:10px">
                            <a href="/edit/book/{{book.id}}" class="btn btn-default btn-xs">책 수정</a>
                        </div>

                    </div>
                </div>
            </div>
        {% empty %}
            <div class="well">
                작성중인 책이 없습니다.
            </div>
        {% endfor %}
        <a href="/edit/book/new" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-plus"></i> 새 책 만들기</a>
    </div>


{% endblock %}

book/templates/profile/profile_comment.html
{% extends "profile/profile_layout.html" %}
{% load staticfiles %}
{% load summary %}

{% block edit_js %}
    <script type="text/javascript" src="{% static "pagination/jquery.pagination.js" %}"></script>
    <script type="text/javascript" src="{% static "apprise/apprise-1.5.min.js" %}"></script>
    <script type="text/javascript" src="{% static "profile/js/comment.js" %}"></script>
{% endblock %}

{% block edit_css %}
    <link type="text/css" href="{% static "pagination/pagination.css" %}" rel="stylesheet"/>
    <link type="text/css" href="{% static  "apprise/apprise.min.css" %}" rel="stylesheet"  />
    <link type="text/css" href="{% static "profile/css/info.css" %}" rel="stylesheet"/>
{% endblock %}

{% block profile_edit_content %}
    {% include "book/include/message.html" %}

    <strong>나의 댓글</strong>
    <hr />
    <div id="recent_comments">

        {% for comment in comments %}
            <div class="question-line">

                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <a class="question-subject" href="{{ comment.page.get_absolute_url }}#comment_{{ comment.id }}">{{ comment.page.subject }}</a>
                            <span class="text-muted" style="margin:0 5px;">:</span>
                            <a href="{{ comment.page.book.get_absolute_url }}">{{ comment.page.book.subject }}</a>
                        </div>

                        <div class="question-summary" style="white-space:pre-wrap;">{{ comment.content|escape|urlize }}</div>

                        <div class="info-timesince">
                            {{ comment.create_time }},
                            <a href="javascript:remove_comment('{{ comment.id }}')">삭제</a>
                        </div>
                    </div>
                </div>

            </div>

        {% empty %}
            <div class="well">
                작성한 댓글이 없습니다.
            </div>
        {% endfor %}


        <div class="row page-area">
            <form name="hiddenForm" id="hiddenForm" method="post" action="{{ request.path }}">
                <input type="hidden" name="total_count" id="total_count" value="{{ total_count }}" />
                <input type="hidden" name="current_page" id="current_page" value="{{ comments.number }}" />
                <input type="hidden" name="per_page" id="per_page" value="{{ per_page }}" />
                <input type="hidden" name="page" id="page" />
            </form>
            <div id="pagination" class="col-md-12" style="margin-top:-10px;"></div>
        </div>

    </div>

    <form name="commentForm" id="commentForm" method="post" action="/profile/edit/comment/remove">
        <input type="hidden" name="comment_id" id="comment_id" />
    </form>
{% endblock %}

book/templates/profile/profile_edit_base.html
{% extends "profile/profile_layout.html" %}

{% block profile_edit_content %}

    {% include "book/include/message.html" %}

    <div class="row">
        <div class="col-md-5">

            <form role="form" method="post" action="/profile/edit/base">{% csrf_token %}
                <div class="form-group">
                    <label for="profile_name">이 름</label>
                    <input type="text" class="form-control" id="id_name" name="name"
                           value="{{ request.user.first_name }}">
                </div>
                {#        <div class="form-group">#}
                {#            <label for="profile_summary">한줄 소개</label>#}
                {#            <input type="text" class="form-control" id="id_summary" name="summary" value="{{ profile.summary|default:"" }}">#}
                {#        </div>#}
                {#        <div class="form-group">#}
                {#            <label for="profile_computer">나의 첫번째 컴퓨터</label>#}
                {#            <input type="text" class="form-control" id="id_computer" name="computer" value="{{ profile.computer|default:"" }}">#}
                {##}
                {#            <p class="help-block">가장 처음 사용했던 컴퓨터명을 입력하세요. (예: 삼보 TG-286)</p>#}
                {#        </div>#}
                {#        <div class="form-group">#}
                {#            <label for="profile_editor">좋아하는 에디터</label>#}
                {#            <input type="text" class="form-control" id="id_editor" name="editor" value="{{ profile.editor|default:"" }}">#}
                {##}
                {#            <p class="help-block">프로그래밍 시 즐겨 사용하는 에디터 (예:vi, eclipse, visual studio)</p>#}
                {#        </div>#}

                <button type="submit" class="btn btn-default" id="submitBtn">저장하기</button>
            </form>
        </div>
    </div>
{% endblock %}

book/templates/profile/profile_edit_password.html
{% extends "profile/profile_layout.html" %}

{% block profile_edit_content %}

    {% include "book/include/message.html" %}
    <div class="row">
        <div class="col-md-5">
            <form role="form" method="post" action="/profile/edit/password">{% csrf_token %}
                <div class="form-group">
                    <label for="id_cpasswd">현재 비밀번호</label>
                    <input type="password" class="form-control" id="id_cpasswd" name="cpasswd" />
                </div>

                <div class="form-group">
                    <label for="id_npasswd">새 비밀번호</label>
                    <input type="password" class="form-control" id="id_npasswd" name="npasswd" />
                </div>
                <button type="submit" class="btn btn-default" id="submitBtn">저장하기</button>
            </form>
        </div>
    </div>
{% endblock %}

book/templates/profile/profile_info.html
{% extends "profile/profile_layout.html" %}
{% load staticfiles %}
{% load summary %}

{% block js %}
    <script type="text/javascript" src="{% static "pagination/jquery.pagination.js" %}"></script>
    <script type="text/javascript" src="{% static "profile/js/info.js" %}"></script>
{% endblock %}

{% block css %}
    <link type="text/css" href="{% static "pagination/pagination.css" %}" rel="stylesheet"/>
    <link type="text/css" href="{% static "profile/css/info.css" %}" rel="stylesheet"/>
{% endblock %}

{% block profile_menu %}
    <div class="user" style="margin-bottom:20px;">
        <a href="/profile/{{ who.id }}" class="btn btn-default btn-block">
            <i class="glyphicon glyphicon-user"></i> {{ who.first_name }}
        </a>
    </div>
    {% if not request.mobile %}
        <div class="well" style="background: #fff;">
            <div style="font-size:16px;margin-bottom:10px;"><strong>코딩도장</strong></div>
            <p>
                코딩도장은 프로그래밍 문제풀이를 통해서 코딩 실력을 수련하는 곳입니다.
            </p>

            <p>
                <a href="http://codingdojang.com">codingdojang.com</a>
            </p>
        </div>
    {% endif %}
{% endblock %}

{% block profile_edit_content %}
    {% include "book/include/message.html" %}

    <ul class="nav nav-tabs">
        <li class="active"><a href="#recent_comments" data-toggle="tab">최근 댓글</a></li>
        <li><a href="#recent_pages" data-toggle="tab">최근 수정 페이지</a></li>
        <li><a href="#recent_books" data-toggle="tab">작성중인 책</a></li>
    </ul>

    <div class="tab-content">
        <div id="recent_comments" class="tab-pane active">
            {% for comment in comments %}
                <div class="question-line">

                    <div class="row">
                        {% if not request.mobile %}
                            <!--
                            <div class="col-md-2">
                                <div class="book-image-box">
                                    <img src="{{ MEDIA_URL }}/{{ comment.page.book.safe_image }}" class="book-image"
                                         onclick="javascript:location.href='{{ comment.page.get_absolute_url }}#comment_{{ comment.id }}'"
                                         title="{{ comment.page.book.subject }}"
                                         style="cursor:pointer"/>
                                </div>
                            </div>
                            -->
                        {% endif %}
                        <div class="col-md-10">
                            <div>
                                <a class="question-subject" href="{{ comment.page.get_absolute_url }}#comment_{{ comment.id }}">{{ comment.page.subject }}</a>
                                <span class="text-muted" style="margin:0 5px;">:</span>
                                <a href="{{ comment.page.book.get_absolute_url }}">{{ comment.page.book.subject }}</a>
                            </div>

                            <div class="question-summary" style="white-space:pre-wrap;">{{ comment.content|escape|urlize }}</div>

                            <div class="info-timesince">
                                약 {{ comment.create_time|timesince }} 전
                            </div>
                        </div>
                    </div>

                </div>

            {% empty %}
                <div class="well">
                    아직 구경만 하고 있어요
                </div>
            {% endfor %}

            {% if total_count > per_page %}
            <div class="row page-area">
                <form name="hiddenForm" id="hiddenForm" method="post" action="{{ request.path }}">
                    <input type="hidden" name="total_count" id="total_count" value="{{ total_count }}" />
                    <input type="hidden" name="current_page" id="current_page" value="{{ comments.number }}" />
                    <input type="hidden" name="per_page" id="per_page" value="{{ per_page }}" />
                    <input type="hidden" name="page" id="page" />
                </form>
                <div id="pagination" class="col-md-12" style="margin-top:-10px;"></div>
            </div>
            {% endif %}
        </div>

        <div id="recent_pages" class="tab-pane">
            {% for page in pages %}
                <div class="question-line">

                    <div class="row">
                        {% if not request.mobile %}
                            <!--
                            <div class="col-md-2">
                                <div class="book-image-box">
                                    <img src="{{ MEDIA_URL }}/{{ page.book.safe_image }}" class="book-image"
                                         onclick="javascript:location.href='{{ page.get_absolute_url }}'"
                                         title="{{ page.book.subject }}"
                                         style="cursor:pointer"/>
                                </div>
                            </div>
                            -->
                        {% endif %}
                        <div class="col-md-10">

                            <div>
                                <a href="{{ page.get_absolute_url }}"
                                   class="question-subject">{{ page.subject }}</a>
                                <span class="text-muted" style="margin:0 5px;">:</span>
                                <a href="{{ page.book.get_absolute_url }}">{{ page.book.subject }}</a>
                            </div>

                            {% if request.mobile %}
                                <div class="question-summary">
                                    {{ page.content|summary|truncatechars:"80" }}
                                </div>
                            {% else %}
                                <div class="question-summary">
                                    {{ page.content|summary|truncatechars:"160" }}
                                </div>
                            {% endif %}

                            <div class="info-timesince">
                                약 {{ page.modify_time|timesince }} 전
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="well">
                    책부터 만들구요
                </div>
            {% endfor %}
        </div>

        <div id="recent_books" class="tab-pane">
            {% for book in books %}
                <div class="question-line">
                    <div class="row">
                        {% if not request.mobile %}
                            <div class="col-md-2">
                                <div class="book-image-box">
                                    <img src="{{ MEDIA_URL }}/{{ book.safe_image }}" class="book-image"
                                         onclick="javascript:location.href='{{ book.get_absolute_url }}'"
                                         style="cursor:pointer"/>
                                </div>
                            </div>
                        {% endif %}
                        <div class="col-md-10">
                            <div>
                                <a href="/book/{{ book.id }}" class="question-subject">{{ book.subject }}</a>
                            </div>

                            <div class="question-summary">
                                저자: {{ book.get_plain_authors }}
                            </div>

                            {% if request.mobile %}
                                <div class="question-summary">
                                    {{ book.summary|summary|truncatechars:"80" }}
                                </div>
                            {% else %}
                                <div class="question-summary">
                                    {{ book.summary|summary|truncatechars:"160" }}
                                </div>
                            {% endif %}

                            <div class="info-timesince">
                                약 {{ book.modify_time|timesince }} 전
                            </div>
                        </div>
                    </div>


                </div>
            {% empty %}
                <div class="well">
                    아직 구상만 하고 있어요
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

book/templates/profile/profile_layout.html
{% extends "book/base.html" %}

{% load staticfiles %}

{% block css %}
    <link type="text/css" href="{% static "common/css/sidenav.css" %}" rel="stylesheet"/>
    {% block edit_css %}{% endblock %}
{% endblock %}


{% block js %}
    <script type="text/javascript" src="{% static "common/js/sidenav.js" %}"></script>
    {% block edit_js %}{% endblock %}
{% endblock %}

{% block content %}
    <div class="content row">
        <div class="col-md-3">
            {% block profile_menu %}
                {% include "profile/profile_menu.html" %}
            {% endblock %}
        </div>
        <div class="page col-md-9" id="profile_edit_content">
            {% block profile_edit_content %}{% endblock %}
        </div>

    </div>
{% endblock %}

book/templates/profile/profile_menu.html
<div class="bs-sidebar hidden-print" role="complementary">
    <ul class="nav bs-sidenav">
        <li{% if request.path == '/profile/edit/base' %} class="active"{% endif %}>
            <a href="/profile/edit/base">기본정보</a>
        </li>
        <li{% if request.path == '/profile/edit/password' %} class="active"{% endif %}>
            <a href="/profile/edit/password">비밀번호 변경</a>
        </li>
        <li{% if request.path == '/profile/edit/book' %} class="active"{% endif %}>
            <a href="/profile/edit/book">나의 책</a>
        </li>
        <li{% if request.path == '/profile/edit/comment' %} class="active"{% endif %}>
            <a href="/profile/edit/comment">나의 댓글</a>
        </li>
    </ul>
</div>