book/urls.py
from django.conf.urls import patterns, url

from book import views
from book import auth_views as auth
from book import old_views as old
from book.feeds import BookFeed

urlpatterns = patterns('',
    # index
    url(r'^$', views.index, name='index'),
    url(r'^tab/(\w+)$', views.index_tab),
    url(r'^book/(?P<book_id>[0-9]+)/rss/$', BookFeed()),

    # book
    url(r'^book/(\d+)$', views.book, name='book'),
    url(r'^book/recommend/(\d+)$', views.book_recommend),
    url(r'^book/comment/save$', views.book_comment_save),
    url(r'^book/comment/remove', views.book_comment_remove),
    url(r'^buy/(\d+)$', views.buy),
    url(r'^buy/save$', views.buy_save),

    # page
    url(r'^(\d+)$', views.page, name='page'),
    url(r'^page/comment/save$',         views.page_comment_save),
    url(r'^page/comment/edit/(\d+)$',   views.page_comment_edit),
    url(r'^page/comment/remove',        views.page_comment_remove),

    # edit
    url(r'^edit/book/(\d+)$', views.edit_book),
    url(r'^edit/book/save$', views.edit_book_save),
    url(r'^edit/book/new$', views.edit_book_new),
    url(r'^edit/book/user$', views.edit_book_user),
    url(r'^edit/book/user/add$', views.edit_book_user_add),
    url(r'^edit/book/user/del$', views.edit_book_user_del),

    url(r'^edit/page/(\d+)$', views.edit_page),
    url(r'^edit/page/save$', views.edit_page_save),
    url(r'^edit/page/new/(\d+)$', views.edit_page_new),
    url(r'^edit/page/image/upload$', views.edit_page_image_upload),
    url(r'^edit/page/image/del$', views.edit_page_image_del),
    url(r'^edit/preview$', views.edit_preview),

    # profile
    url(r'^profile/(\d+)$', 'book.profile_views.info'),
    url(r'^profile/edit/base$', 'book.profile_views.edit_base'),
    url(r'^profile/edit/password$', 'book.profile_views.edit_password'),
    url(r'^profile/edit/book$', 'book.profile_views.book'),
    url(r'^profile/edit/comment$', 'book.profile_views.comment'),
    url(r'^profile/edit/comment/remove$', 'book.profile_views.remove_comment'),

    # help
    url(r'^help/(\w+)$', views.help),

    # feedback
    url(r'^feedback$', views.feedback),

    # --------------------------------------------

    # authentication
    url(r'^loginForm$', auth.loginForm),
    url(r'^logout$', auth.logout),
    url(r'^joinForm$', auth.joinForm),
    url(r'^login$', auth.login),
    url(r'^join$', auth.join),
    url(r'^passwdForm$', auth.passwdForm),
    url(r'^passwd/send$', auth.passwd_send),

    # social login
    url(r'^login/auth$', auth.social_auth),
    url(r'^login/auth/error$', auth.social_auth_error),

    # old
    url(r'^read', views.index),

    # old api
    url(r'^api/page/(\d+)$', old.api_page),
    url(r'^api/toc$', old.api_toc),
    url(r'^api/comment$', old.api_comment),
)

wikidocs/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.views.generic.base import RedirectView

from book import views
from book.models import Book, Page

admin.autodiscover()

def get_sitemap():
    book_dict = {
        'queryset': Book.objects.filter(open_yn="Y"),
        'date_field': 'create_time',
    }

    page_dict = {
        'queryset': Page.objects.filter(book__open_yn="Y", open_yn="Y"),
        'date_field': 'modify_time',
    }

    sitemaps = {
        'docs': GenericSitemap(book_dict, priority=0.5),
        'page': GenericSitemap(page_dict, priority=0.5),
    }
    return sitemaps


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wikidocs.views.home', name='home'),
    url(r'', include('book.urls')),
    url(r'', include('social_auth.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': get_sitemap()}),

    url(r'^apps/', RedirectView.as_view(url='/', permanent=False), name='index'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if not settings.DEBUG:
#     urlpatterns += patterns('',
#         url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': settings.BASE_DIR+"/book/static", 'show_indexes': True})
#     )

handler404 = views.page_404
handler500 = views.page_500

book/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Max
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.html import format_html

import datetime
import os


class Ip(models.Model):
    ip = models.CharField(max_length=30, unique=True, db_index=True)

    def __unicode__(self):
        return self.ip


OPEN_YN_CHOICES = (
    ("Y", u"공개"),
    ("N", u"비공개"),
)
ADV_YN_CHOICES = (
    ("Y", u"예"),
    ("N", u"아니오"),
)
CCL_LEFT = (
    ("by", u"예"),
    ("by-nc", u"아니오"),
)
CCL_RIGHT = (
    ("-", u"예"),
    ("-sa", u"동일한 이용허락조건을 적용하는 경우에만"),
    ("-nd", u"아니오"),
)
class Book(models.Model):
    user = models.ManyToManyField(User, verbose_name=u"저자")
    creator = models.ForeignKey(User, related_name="book_creator", verbose_name=u"지은이")
    subject = models.CharField(max_length=100, verbose_name=u"책 제목")
    create_time = models.DateTimeField(default=datetime.datetime.now)
    modify_time = models.DateTimeField(default=datetime.datetime.now)
    viewer = models.ManyToManyField(Ip, null=True, related_name="book_viewer")
    recommend = models.ManyToManyField(Ip, null=True, related_name="book_recommend")
    open_yn = models.CharField(max_length=1, default="N", choices=OPEN_YN_CHOICES, verbose_name=u"공개/비공개")
    image = models.ImageField(upload_to="book/", null=True, verbose_name=u"책 이미지")
    summary = models.TextField(null=True, blank=True, verbose_name=u"책 설명")
    ccl_left = models.CharField(max_length=20, null=True, choices=CCL_LEFT, verbose_name=u"저작물의 영리목적 이용을 허락합니까?")
    ccl_right = models.CharField(max_length=20, null=True, choices=CCL_RIGHT, verbose_name=u"저작물의 변경을 허락합니까?")
    adv_yn = models.CharField(max_length=1, default="N", choices=ADV_YN_CHOICES, verbose_name=u"광고를 표시합니까?")
    adv_content = models.TextField(null=True, blank=True, verbose_name=u"광고 내용")
    adv_mobile_content = models.TextField(null=True, blank=True, verbose_name=u"모바일 광고 내용")

    def __unicode__(self):
        return self.subject

    def ccl(self):
        nvl = lambda s: '' if s is None else str(s)
        result = nvl(self.ccl_left) + nvl(self.ccl_right)
        if result and result[-1] == "-": result = result[:-1]
        return result

    def price(self):
        sell = Sell.objects.filter(book=self)
        if sell: return sell[0].price
        return 0

    def get_absolute_url(self):
        return "/book/{0}".format(self.id)

    def get_first_page(self):
        if self.page_set.count() > 0:
            result = self.page_set.filter(open_yn='Y').order_by("seq")
            if result: return result[0]
        return ""

    def is_sell(self):
        return Sell.objects.filter(book=self).count() > 0

    def is_owner(self, user):
        return user in self.user.all()

    def is_creator(self, user):
        return user == self.creator

    def safe_image(self):
        if not self.image: return "no_image.gif"
        else: return self.image

    def get_plain_authors(self):
        result = []
        for user in self.user.all():
            result.append(user.first_name)
        return ", ".join(result)

    def last_modify_time(self):
        result = Page.objects.filter(book=self).aggregate(max=Max('modify_time'))
        return result.get('max', "")

    def recent_page_comments(self, limit=10):
        return PageComment.objects.filter(page__book=self).order_by("-create_time")[:limit]

    def recent_pages(self, limit=10):
        return self.page_set.filter(open_yn='Y').order_by("-modify_time")[:limit]


def get_upload_path(instance, filename):
    if isinstance(instance, PageImage):
        return os.path.join("page", "%d" % instance.page.id, filename)
    else:
        # return "page/%s/%s" % (instance.id, filename)
        return os.path.join("page", "%d" % instance.id, filename)


class Page(models.Model):
    subject = models.CharField(max_length=100, verbose_name=u"제목")
    content = models.TextField(verbose_name=u"내용")
    book = models.ForeignKey(Book, verbose_name=u"책선택")
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name=u"부모페이지")
    create_time = models.DateTimeField(default=datetime.datetime.today)
    modify_time = models.DateTimeField(default=datetime.datetime.today)
    viewer = models.ManyToManyField(Ip, null=True, related_name="page_viewer")
    open_yn = models.CharField(max_length=1, default="Y", choices=OPEN_YN_CHOICES, verbose_name=u"공개/비공개")
    seq = models.IntegerField(default=0)
    depth = models.IntegerField(default=0)
    image = models.ImageField(upload_to=get_upload_path, null=True, blank=True, verbose_name=u"이미지삽입")

    def __unicode__(self):
        return self.subject


    def subject_margin(self):
        return self.depth * 20

    def depth_subject(self):
        return format_html(u'<span style="padding-left: {0}px;">{1}</span>',
                           self.subject_margin(),
                           self.subject)

    def get_absolute_url(self):
        return "/{0}".format(self.id)

    def _make_parents(self, page, pages=None):
        if page.parent and page.parent != page:
            pages.insert(0, page.parent)
            self._make_parents(page.parent, pages)

    def get_parents(self):
        result = []
        self._make_parents(self, result)
        return result

    def prev(self):
        try:
            return Page.objects.filter(book=self.book, seq__lte=self.seq-1, open_yn="Y").order_by("-seq")[0]
        except:
            return ""

    def next(self):
        try:
            return Page.objects.filter(book=self.book, seq__gte=self.seq+1, open_yn="Y").order_by("seq")[0]
        except:
            return ""

    def is_closed_for_buy(self):
        return self.open_yn == "N" and self.book.is_sell()


class PageImage(models.Model):
    page = models.ForeignKey(Page)
    image = models.ImageField(upload_to=get_upload_path, null=True, blank=True, verbose_name=u"이미지")


class Sell(models.Model):
    book = models.ForeignKey(Book)
    price = models.IntegerField()
    filename =  models.CharField(max_length=100, verbose_name=u"파일명")

    def __unicode__(self):
        return self.book.subject


SEND_YN_CHOICES = (
    ("Y", u"발송완료"),
    ("N", u"미발송"),
)

MONEY_YN_CHOICES = (
    ("Y", u"입금완료"),
    ("N", u"미입금"),
)
class Buy(models.Model):
    book = models.ForeignKey(Book)
    buyer = models.CharField(max_length=100, verbose_name=u"구매자")
    email = models.CharField(max_length=200, verbose_name=u"이메일")
    telno = models.CharField(max_length=20, verbose_name=u"전화번호")
    create_time = models.DateTimeField(default=datetime.datetime.today, verbose_name=u"구매일시")
    send_yn = models.CharField(max_length=1, default="N", choices=SEND_YN_CHOICES, verbose_name=u"발송여부")
    money_yn = models.CharField(max_length=1, default="N", choices=MONEY_YN_CHOICES, verbose_name=u"입금여부")

    def __unicode__(self):
        return u"%s(%s) - %s (%s원)" % (self.buyer, self.email, self.telno, self.book.price())


class BookComment(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name=u"작성자", null=True, blank=True)
    book = models.ForeignKey(Book)
    content = models.TextField(verbose_name=u"댓글내용")
    create_time = models.DateTimeField(default=datetime.datetime.today)


class PageComment(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name=u"작성자", null=True, blank=True)
    page = models.ForeignKey(Page)
    content = models.TextField(verbose_name=u"댓글내용")
    create_time = models.DateTimeField(default=datetime.datetime.today)


@receiver(post_delete, sender=PageImage)
def photo_post_delete_handler(sender, **kwargs):
    pageImage = kwargs['instance']
    storage, path = pageImage.image.storage, pageImage.image.path
    storage.delete(path)

book/forms.py
# -*- coding: utf-8 -*-
from django import forms

class BookEditForm(forms.Form):
    subject = forms.CharField(max_length=100, required=True, label=u"책 제목")


class PageEditForm(forms.Form):
    subject = forms.CharField(max_length=100, required=True, label=u"페이지 제목")
    content = forms.CharField(required=True, label=u"페이지 내용")


class BuyForm(forms.Form):
    buyer = forms.CharField(max_length=100, required=True, label=u"신청자 이름")
    email = forms.EmailField(max_length=100, required=True, label=u"이메일")
    telno = forms.RegexField(max_length=15, regex=r"\d{2,3}[-]\d{3,4}[-]\d{4}", required=True, label=u"전화번호")
    agree = forms.BooleanField(required=True, label=u"환불규정")

book/templates/book/include/book_comment.html
{% for comment in book.bookcomment_set.all|dictsort:"create_time" %}
    <div class="comment comment_border_top">

        <span style="white-space:pre-wrap;">{{ comment.content|escape|urlize }}</span>
        <span style="font-size:11px;color:#888;">
            - {{ comment.user.first_name }}, 약 {{ comment.create_time|timesince }} 전
            {% if comment.user == user %}
            , <a href="javascript:remove_comment('{{ comment.id }}')">삭제</a>
            {% endif %}
        </span>
    </div>
{% endfor %}

book/templates/book/include/edit_book_author.html
<span class="label label-danger">{{ book.creator.first_name }}</span>
{% for author in book.user.all %}
    {% if author != book.creator %}
    <a class="label label-info" href="javascript:user_del('{{ author.id }}')" title="공동저자 취소">{{ author.first_name }} <i style="margin-top:3px;" class="glyphicon glyphicon-remove"></i></a>
    {% endif %}
{% endfor %}

book/templates/book/include/edit_book_user.html
{% if users %}
<ul class="edit-book-user">
    {% for su in users %}
        <li>{{ su.first_name }} (<a href="javascript:user_add('{{ su.id }}')" style="font-size:12px;">추가</a>)</li>
    {% endfor %}
</ul>
{% endif %}

book/templates/book/include/edit_page_image.html
<ul>
    {% for pageImage in page.pageimage_set.all %}
        <li>
            <a id="pageimage_{{ pageImage.id }}" href="{{ MEDIA_URL }}{{ pageImage.image }}" target="_new">{{ pageImage.image }}</a>
            <a class="markdown_tooltip" href="javascript:remove_image('{{ pageImage.id }}')" title="현재 이미지를 삭제합니다."><i style="margin-top:4px" class="glyphicon glyphicon-remove"></i></a>
            <a class="markdown_tooltip" href="javascript:apply_image('{{ pageImage.id }}')" title="현재 이미지를 마크다운 에디터에 적용합니다."><i style="margin-top:4px" class="glyphicon glyphicon-ok"></i></a>
        </li>
    {% endfor %}
</ul>

book/templates/book/include/edit_preview.html
{% load staticfiles %}
{% load markdown_tags %}

<link type="text/css" href="{% static "highlight.js/styles/default.css" %}" rel="stylesheet"  media="screen" />
<link type="text/css" href="{% static "book/css/markdown.css" %}" rel="stylesheet"  media="screen" />

<div class="page-content">
    {{ preview_content|my_markdown }}
</div>

book/templates/book/include/edit_toc.html
<div id="_toc" style="display:none;">
    <div class="toc toc-edit{% if request.mobile %} hide toggle-toc{% endif %}">
        <div class="toc-subject">
            <a class="selected_toc" href="/edit/book/{{ book.id }}">{{ book.subject }}</a>
            {% if book.open_yn == "N" %}
            <i class="glyphicon glyphicon-lock"></i>
            {% endif %}
        </div>
        <ul style="overflow-y:auto;" id="edit_toc_box">
            {% for toc_page in toc %}
            <li class="{% if toc_page == page %}selected_toc_li{% endif %}">
                <a href="/edit/page/{{ toc_page.id }}" class="{% if toc_page == page %}selected_toc{% endif %}">
                    <span style="width:220px;white-space:nowrap;overflow:hidden;display:block;" title="{{ toc_page.subject }}">
                        <span style="padding-left:{{ toc_page.subject_margin }}px">
                        {% if toc_page.open_yn == "N" %}
                        <i class="glyphicon glyphicon-lock"></i>
                        {% endif %}
                        {{ toc_page.subject }}
                        </span>
                    </span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <a href="/edit/page/new/{{ book.id }}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-plus"></i> 페이지 추가</a>

    {% if request.mobile %}
    <div style="margin:10px 0 10px 0">
        <button class="btn btn-default btn-sm" id="show_toc_btn"><i class="glyphicon glyphicon-folder-open"></i> 목차 펼치기</button>
    </div>
    {% endif %}

</div>

<input type="hidden" name="request_mobile" id="request_mobile" value="{% if request.mobile %}1{% else %}0{% endif %}" />

book/templates/book/include/markdown_toolbar.html
<div class="toolbar clearfix">
    <span class="button-h1" accesskey="1" title="Heading 1"><img src="/static/markdown/images/h1.png" /></span>
    <span class="button-h2" accesskey="2" title="Heading 2"><img src="/static/markdown/images/h2.png" /></span>
    <span class="button-h3" accesskey="3" title="Heading 3"><img src="/static/markdown/images/h3.png" /></span>
    <span class="button-bold" accesskey="b" title="Bold text"><img src="/static/markdown/images/bold.png" /></span>
    <span class="button-italic" accesskey="i" title="Italic text"><img src="/static/markdown/images/italic.png" /></span>
    <span class="divider">&nbsp;</span>
    <span class="button-bullets" accesskey="l" title="Bullet List"><img src="/static/markdown/images/bullets.png" /></span>
    <span class="button-numbers" accesskey="n" title="Ordered list"><img src="/static/markdown/images/numbers.png" /></span>
    <span class="divider">&nbsp;</span>
    <span class="button-sourcecode" accesskey="k" title="Source code"><img src="/static/markdown/images/source_code.png" /></span>
    <span class="button-quote" accesskey="q" title="Quotation"><img src="/static/markdown/images/document_quote.png" /></span>
    <span class="divider">&nbsp;</span>
    <span class="button-link" accesskey="l" title="Insert link"><img src="/static/markdown/images/link.png" /></span>
    <span class="button-image" accesskey="p" title="Insert picture/image"><img src="/static/markdown/images/picture.png" /></span>
    <a href="http://en.wikipedia.org/wiki/Markdown" target="_new" class="label label-default pull-right" style="margin-top:5px;margin-left:5px;">마크다운이란?</a>
    <a href="javascript:preview();" class="label label-default pull-right" style="margin-top:5px;margin-left:5px;">미리보기</a>
    <a href="javascript:fullscreen();" class="label label-default pull-right" style="margin-top:5px;margin-left:5px;">전체화면 편집</a>
{#    <a href="#" class="markdown_tooltip label pull-right" style="margin-top:5px;" rel="tooltip" data-toggle="tooltip"#}
{#       title="이미지 업로드는 링크만 가능합니다. 다른 곳(예:드롭박스)에 이미지를 먼저 업로드 하신 후에 좌측의 이미지 버튼을 이용하여 이미지를 삽입 해 주시기 바랍니다.">이미지업로드</a>#}
</div>


<div class="modal" id="markdownPreview" tabindex="-1" role="dialog" aria-labelledby="markdownPreviewLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close closePreview" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">미리보기</h4>
        </div>
        <div class="modal-body" id="markdown_preview_content"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default closePreview" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

book/templates/book/include/message.html
{% if error_message %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ error_message }}
    </div>
{% endif %}

{% if ok_message %}
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ ok_message }}
    </div>
{% endif %}

book/templates/book/include/page_comment.html
{% for comment in page.pagecomment_set.all|dictsort:"create_time" %}
    <div class="comment comment_border_top">
        <a name="comment_{{ comment.id }}"></a>
        <span style="white-space:pre-wrap;">{{ comment.content|escape|urlize }}</span>
        <span style="font-size:11px;color:#888;">
            -
            {% if comment.user %}
                {{ comment.user.first_name }},
            {% else %}
                {{ comment.name }},
            {% endif %}
            {{ comment.create_time }}
            {% if comment.user == user %}
                , <a href="/page/comment/edit/{{ comment.id }}">수정</a>
                , <a href="javascript:remove_comment('{{ comment.id }}')">삭제</a>
            {% endif %}
        </span>
    </div>
{% endfor %}

book/templates/book/include/page_comment_edit.html
{% extends "book/base.html" %}

{% load staticfiles %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="lead">
                <strong>댓글 수정</strong>
            </div>
            <form role="form" method="post" action="/page/comment/edit/{{ comment.id }}">{% csrf_token %}

                <div class="form-group">
                    <textarea class="form-control" rows="5" id="id_content"
                              name="content">{{ comment.content }}</textarea>
                </div>

                <button type="submit" class="btn btn-default" id="submitBtn">수정하기</button>
                <a href="/{{ comment.page.id }}#comment_{{ comment.id }}" class="btn btn-default">취소하기</a>
            </form>
        </div>
    </div>

{% endblock %}

book/templates/book/include/toc.html
{# 목차#}
<div class="toc{% if request.mobile %} hide{% endif %}">
    <div class="toc-subject clearfix">
        {% if not page %}
            <span class="glyphicon glyphicon-chevron-right"></span>
        {% endif %}
        <a class="selected_toc" href="{{ book.get_absolute_url }}">{{ book.subject }}</a>
        {% if book.open_yn == "N" %}
            <span class="glyphicon glyphicon-lock"></span>
        {% endif %}
        {% if book.price > 0 %}
            {#        <a href="/buy/{{ book.id }}" class="label label-warning pull-right" title="e-book 구매하기"><i class="icon-shopping-cart icon-white"></i> e-book</a>#}
        {% endif %}
    </div>
    <ul class="toc-area">
        {% for toc_page in toc %}
            <li class="{% if toc_page == page %}selected_toc_li{% endif %}">
                <a href="{{ toc_page.get_absolute_url }}" class="{% if toc_page == page %}selected_toc{% endif %}">
                <span style="width:220px;white-space:nowrap;overflow:hidden;display:block;"
                      title="{{ toc_page.subject }}">
                    <span style="padding-left:{{ toc_page.subject_margin }}px">
                    {% if toc_page.open_yn == "N" %}
                        <i class="glyphicon glyphicon-lock"></i>
                    {% endif %}
                        {% if toc_page == page %}
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        {% endif %}
                        {{ toc_page.subject }}
                    </span>
                </span>
                </a>
            </li>
        {% endfor %}
    </ul>
    <div style="display:none;" class="text-center toc-open">
        <a href="javascript:open_toc();">
            <i class="glyphicon glyphicon-chevron-down"></i> 전체 목차보기
        </a>
    </div>
</div>

{% if request.mobile %}
    <button class="btn btn-default btn-sm" id="show_toc_btn" style="margin-bottom:10px;">
        <i class="glyphicon glyphicon-folder-open"></i> 목차 펼치기
    </button>
{% endif %}

{% if not request.mobile %}
    <div class="well toc-ads" style="background: #fff;display:none;">
        <div style="font-size:16px;margin-bottom:10px;"><strong>CleanCode</strong></div>
        <p>
            CleanCode는 한국의 스택오버플로우를 꿈꾸는 개발자 커뮤니티입니다.
        </p>

        <p>
            <a href="http://cleancode.kr">cleancode.kr</a>
        </p>
    </div>
{% endif %}

<input type="hidden" name="request_mobile" id="request_mobile" value="{% if request.mobile %}1{% else %}0{% endif %}" />